apiVersion: v1
kind: Secret
metadata:
    name: org-dataverket-runner-secret
    namespace: forgejo-runners
type: Opaque
stringData:
    .runner: ENC[AES256_GCM,data:gPcTdVV4vq0iHsAzpVEaHvvT16je3mb8YCf9CKUI2moiPVixDWW/hZgtX/H7+a5pfmvf0fJ50UknLPHh/rl3l/9uUKTIYNlBJPcTL0CTN+rrDFXL7fC6tjBdWLB2dRu5hOhsjUp7cRRjyFLg0JJUvaBOtduq71Hj07x0pSzRyj1fum9ztOvNAO+SK+Vt9eCD7UWXVzeBP0wSjx6Ml8SbnhXlszilI/lgwdzgq/KXHIwgJ/4v+Gl0RopuF62MNNwaWLr7ubcHg2AtWevswqyC8mG5IeW8VCw3BY5GHwmont8yQc4Lsvel0IEqVoixW+2pb5r2GtweBwrug8lEX/EvFHTNbSxO7dd3R9RozGOj4Z+hn8YHDGlZt4AYNmmSDIbDkdOSNhdj5sw17LZiIk05SK/56Z7eP9fVo35vy0phFc6mReGyoP0AsB6NiQ/zj8OAxSMmrXj/f3el+yRboZM07Eg99JqWp3AnotYkYsJhpKZW0MyHUdcgPylWbEmKzao+FcsVIXyZZ0x2LYmfrv459OAFn01uFFKVUuGy2KjqapW5L4nECUs61vQE6arw2mYX1KqDvnZKoWpEkzBpyChewwdJPoGbvpSQMzJ9pY/l6mL9S126wzYnkDLvbBVbS3tihlKxqiRIxncSEi4GGThD8ldHEp/C6tgfUIksDtlwuyNI8NV+zPJkSva+ArzVHH7R6AGwtqjAxPchpb3Xi/ggFVV0Td4+6GYopA==,iv:+IysXq7Kcc1YFwbPBFqVyGy+Xhpcxhn0GzwPSGO2N6M=,tag:3wUDY7EHl2qBFV0QvXfLCA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubmZ5WW1yNStsNTlzTlhI
            Mm0zdC9FUDN3cTZuYXRJVmtvWWxiN0J6VG1nCmt6STkzeWx6QWtGVVduQ3QrSmNV
            L3liVXZQd2x4MmtQeGxpZWdnUWcvZ0EKLS0tIDNXekh6Wnk0ZWxiWWRMR0F3VWtU
            Y1FCd1l0T2JlYWZFTmUvTEtKemdIMWcKrOAQUANC3RmKg9T9aVUoBf3d/4qODIVy
            tsssVcDu3G3YFkdZZ+89nK7v+eyTZfAgbhtBHXPGjxX/eM2IztQewQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g3x9w6x6wvskhtgn33wufdp2yn7vy8u3lf0f29r8nnkxuwrca4pscvydqy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDhENXluZyBBeEVuNmZx
            MmJKZDVuN0R4eWpCMVp4Mnc4bm5vNVRoMlArZ1FWaWJQSVNhbgphZFNjRWdEZWRF
            S3FhRmpJUzlOTW40TFlVYks5NExpVzRKUU92cXRQY3NBCi0tLSBUa3FEMUEyc1ZF
            NWRwWGF1WVYwcFg2TzZLQ2IydlpORUN4ZkFwT1JJUlQ0CoRDikYE9/i2fvJeFkG5
            reNcpOt6vzJQ7iK+CohZCti1TiqyFMvu0OPVD5xnoc4r92sqQ+HilI+SDXvbDfCw
            RQ8=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q0d8krn6cy32uun9ygwvrd373sp04hnjfpdfazy9lhpz70h3hauf2kgjzmx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDNweXF3ZyBBM0x5VzVj
            TUI0ZThxcVB6azc2NTQ0aXJWc1Y3UVo4dGRaOEQvRkhOT0NUawpwZzJaODVPbU9V
            bWV5N1Y2RW51OC85V0hzbFRJTnQxSFNxaldjamNSbW9ZCi0tLSBXVW5tSktMUzli
            V0c1OHNkVDZmazZjMzFqeFFsY0hoZVRGUUdiQU1iS2FnCqBXvWr5QTn9aL1FzODN
            1+QMyh5NduJcEkR2ZcDYnvoLXnUUdmapEr2MFkeQVWBSYB+5vG1DkYtOZL9NrZCW
            DIg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwtampyck0fvqdlcfwjk3yhcu2s3gvrn67wdvxyv8uty6v5zpkxq76kzrpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T11:58:49Z"
    mac: ENC[AES256_GCM,data:u7mY3Gfttjn5EYiHnvm7bpBsV/nz3Ld2cTRP1m+oZ61gwnj0ojhRJDG5lxcIV64Kels9BvVY5/wtnRJj0WcQR8hs8Ec492q8HDZYEiPwXWd/jvh3so0xlW65h1ivuUHL6mPZ7vmu1Fo9VM3csdpGmaCMkeJthrx4rdx7Wy1cDwA=,iv:2m79GDFM9jePGQKkHPtJM4uKNgSQZ7aVVhdKnZW73+c=,tag:9D7dlBuxIVF5TZhWy5RwBw==,type:str]
    version: 3.13.3
