# Users zot accepts for push (see configmap.yaml accessControl). bcrypt entries; the plaintext lives in
# zot-ci-credentials.enc.yaml, the source the factory's vault copies from.
apiVersion: v1
kind: Secret
metadata:
    name: zot-htpasswd
    namespace: zot
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:kWaqgdl2eJcysJ5VfLlxafgiR0h/DOPKOXCgTNmsfJqya98VlQqlU3xpCAiGBbZw+BqPA5nl0mtc4WQ5zwdIpZ6OTuyTii+m,iv:L/LSWppB0X1w0ZYned0EyQngTmQeWUQlSMZrwFbCM5k=,tag:tgLLDo/u4cAbNxLgTgfGbg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDhENXluZyBBZ1pDUk82
            c1Z4anBkOVlDZWtlelhCb2NERDBYOHVyVWhrY2tLQ3IyQm85cwp1SWNtMGpUYjZs
            MnR3OXY5S3h0SVFwd0kxRGlrNDVMSGNiQnZXTERXWXhnCi0tLSB4TUd2SDUyamN6
            cjU4d1JERTQwNlYyN015UDZoYS9DZ3RXdDhUZWkwZk5ZCkG4byFnlRpVMdwNbw/I
            t3/OOhpToul6vB8EBCeGFPt5JrZJZv4SJUt0qI/8EIijgxb6Sz3iu5PmLvDxbVMd
            xXA=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q0d8krn6cy32uun9ygwvrd373sp04hnjfpdfazy9lhpz70h3hauf2kgjzmx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4bHN4RzZ2U092MHlCbk9w
            Q2YzdFN2SENuMVRSRUNhYjNrSXZPOFY5UWpBCjgyNENZWTBIZHJvUVhFT3VFMlg0
            UnpxYW9ia1ZScmVlbklsUjdETW5ZQncKLS0tIHFBTFZwcWk0elk3cTAzQXVHcjFt
            QmJSR1JZdzhzWGpnbnF0aDVtV1ZmNmMKCCBNpzpCuIrpz3xsCBSAHt1Q8gw+0tYK
            2O/kBd2nOIy5aD0WHkXO2C4I3FO3Hvq7s/yDCwh5zibGPw3aPYEsQQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g3x9w6x6wvskhtgn33wufdp2yn7vy8u3lf0f29r8nnkxuwrca4pscvydqy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDNweXF3ZyBBMUFpU08x
            ejBGdEZ5Mkd2emlreWNtQzFYUnlIS2o4QnFxQk8vVTBHd3RtVApWR3VQQ0F5NHJM
            SERBOXp5OWF1RWxNWVRvdWlRaDdaRXlpOUVuUEdsVzJzCi0tLSB1MmJydkt3VTdq
            ZldVYmxaY0FGNHZOeW16TEI2UTkxUWlLelFIU2dHY01FCkvLLfVirEPjZswI6M9c
            DRyooV2+6UIR9ctcwh3T2sluAxsIPJpG1hawRXRbUs1zHu9397Z9k7vbAsPLDAXQ
            RgM=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwtampyck0fvqdlcfwjk3yhcu2s3gvrn67wdvxyv8uty6v5zpkxq76kzrpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T14:18:25Z"
    mac: ENC[AES256_GCM,data:U8W07HgyiUFR/4BXStDh18rzqPWXO0DReSd/fi4LD3AsoapAY3n3kVpcgx/yBTyD85sRSxiVlgVjDfdFbayfzx2FhGLCF3kkF5uRyBm48G4VxnJocxpHkiqasZlx6gSls4KSefX/ICwvu55xeJRHAPgEYncrs06bkGPFxjPdo4A=,iv:aCHH9BlM/mPnBSaALssZkKmVqUlsyPdapeiN56hVaYY=,tag:lyU3jJtBmVvuWPoEnooDng==,type:str]
    version: 3.13.3
