apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: forgejo-runner-helm
  namespace: flux-system
spec:
  interval: 10m
  url: https://code.forgejo.org/forgejo-helm/forgejo-runner.git
  ref:
    branch: main
    commit: 3ae5398156088d703afb5aefc1d6f38574ab30a6
