type: '@dataverket/zitadel/settings'
typeVersion: 2026.09.29.1
id: 3748c850-0149-4721-94ea-cf06acefe60d
name: zitadel-settings
version: 1
tags: {}
globalArguments:
  apiUrl: 'https://zitadel.dataverket.org'
  keyJsonFile: '~/.config/zitadel/fabrikk-infra-reader.json'
methods: {}
