type: '@swamp/kubernetes/secret'
typeVersion: 2026.08.01.1
id: 61989555-a71f-4677-9514-e8b6355ad53e
name: dataverket-prod-secrets
version: 1
tags: {}
globalArguments:
  namespace: forgejo-runners
  context: dataverket-prod-admin
methods: {}
