apiVersion: v1
kind: Service
metadata:
  name: nordhost-webhook
  namespace: "default"
  labels:
    app: nordhost-webhook
    chart: nordhost-webhook-0.1.0
    release: nordhost-webhook
    heritage: Helm
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: nordhost-webhook
    release: nordhost-webhook


