apiVersion: apps/v1
kind: Deployment
metadata:
  name: occm-lb-test
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: occm-lb-test
  template:
    metadata:
      labels:
        app: occm-lb-test
    spec:
      containers:
        - name: web
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: occm-lb-test
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: occm-lb-test
  ports:
    - port: 80
      targetPort: 80

