apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.nordhost-integrator
  annotations:
    cert-manager.io/inject-ca-from: "cert-manager/nordhost-webhook-webhook-tls"
spec:
  group: nordhost-integrator
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: nordhost-webhook
    namespace: cert-manager
  version: v1alpha1
