apiVersion: v1
kind: Secret
metadata:
    name: www-secrets
    namespace: www
type: Opaque
stringData:
    SIGNAL_GROUP_LINK: ENC[AES256_GCM,data:3zF/Dt2CROgh5BW4p42h0epSyyBE7U2IFOm3aXaLlVqjqzy0jqANcb1c1+9crtQZ0dj24mX59mhlksFQI4goNE34UWujT7h/Pa1wKeElQKPRx3Q6787BOoSKqjjcJg==,iv:eMwemMl4mc4nDss86dIaymavw6IFBx9jFd5De8JC9pc=,tag:g7C3SZJwJKDW6b8RwLotpA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDhENXluZyBBNElJWUlI
            WllYT1Z1MG02OVlhTWtRVWwwTVRMeWQzYkVyd2k4SkNRRVVUWgprYlNPWWFKa3VK
            YXQ1VitiRGd0dGhHVlRQWDI4aFh0cjRxcm10VTRrRm5zCi0tLSBES09MRG00Z2dv
            QnVuMGV4NVVuWHlqcm0vd3lpTDI4NzBFNEFiWGV2K25nCkQ0fNGEZC1+KXzz/VIL
            R58DMXaJ5iSWOSYs0+o1e1sL6s/BkIDD5WpPUQ/UCy4zpVlfr95L4mhczLxeJt62
            a6g=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q0d8krn6cy32uun9ygwvrd373sp04hnjfpdfazy9lhpz70h3hauf2kgjzmx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhNE9OT2xSamlzdThiZHFj
            elFOY0NPbFVsTlZwME10aDYwdWNwNmdtR1hrCjFtRVNlRm83QUF0QkVodG9WTXhY
            MU5SbHdlMG5zc0FXa1BZaDhTNUtZeTAKLS0tIEgwZHAwdUx4YXZXbyt4SGRvbHl1
            bHR1bC9KOHk4em1iMTA5aDNtMUZwR0UK6aaKawdjjFw1vUB3Ljoc9yHggjtc6THs
            aKv97PhMLXK/2X3X3kQy5NMKIGc7/2syLXgojCAPadYgdaRV+LGy4Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g3x9w6x6wvskhtgn33wufdp2yn7vy8u3lf0f29r8nnkxuwrca4pscvydqy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDNweXF3ZyBBM25peEpB
            amY5Q2hNb284aGY0UkZDcEtQZWhpN3B3YkpVdzNXamM2WXp1bgpoamdtWlFQbGsy
            NGVNUUptTWV6NFZzd0YraXY3Q0Q3MHk4WmxvWmxVVlZvCi0tLSArRVhyUDNyUDZ2
            SEhNUGFOK2kyNlgrZS9UQ29vd0NUR3UzbUlNY2Y5eTMwCgYQ0SqiFSNTOdQ+Vbwx
            aXZgGIu3eTShEhW7h+A9hY/UVlRo5KuvGsdH4NNvmGfQ9yCjWtxQfXyOjPLGKq3w
            pdU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwtampyck0fvqdlcfwjk3yhcu2s3gvrn67wdvxyv8uty6v5zpkxq76kzrpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T13:03:14Z"
    mac: ENC[AES256_GCM,data:2DN5NoQRLGQabmE/dSFdtd3z++3f92Ym0eiUz2XdOuf8jw7yZqO8RgOB/rTWUUFKzm4RB8tWVZb0avVX6y8en4TSSIH7JCO8PwyBPAn5YHTg/XESMIQsS4t+ILIamkvi4hNhrOMhNt83KdfGHP0VfiEgIK+0VCzHGencpxhal/8=,iv:vmeFoCRmTeBMDBzlmIq+4gFSbl4PAv3ufvaBxHh8ado=,tag:mdm9U0MrYJJnz+NkOdh6Tw==,type:str]
    version: 3.13.3
