type: '@swamp/kubernetes/event'
typeVersion: 2026.08.01.1
id: a828964b-f7e5-4c02-8a12-77e9e70ac96b
name: forgejo-events
version: 1
tags: {}
globalArguments:
  namespace: forgejo
  context: dataverket-prod-admin
methods: {}
