apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nodeplugin-ds.yaml
  - nodeplugin-rbac.yaml
  - controller-ds.yaml
  - controller-rbac.yaml
  - csi-driver.yaml
  - storageclass.yaml
