type: '@dataverket/openstack/application-credential'
typeVersion: 2026.09.18.1
id: 32f80b05-87f1-4fbb-9b49-1c3380cc74e7
name: openstack-application-credential
version: 1
tags: {}
globalArguments:
  cloud: fabrikk-infra
  openstackPath: openstack
  concurrency: 4
methods: {}
