type: '@mccormick/omni/inventory'
typeVersion: 2026.06.09.1
id: 38515f19-7225-4d24-850b-256c10cc7bb1
name: omni
version: 1
tags: {}
globalArguments:
  endpoint: 'https://dataverket.eu-central-1.omni.siderolabs.io'
  serviceAccountKey: '${{ vault.get(infra, omni/service_account_key) }}'
methods: {}
