apiVersion: v1
kind: Secret
metadata:
    name: forgejo-zitadel-oauth-secret
    namespace: forgejo
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:k0mX6gIucNY3+SdML2/mxlUI,iv:NKyUTi+38BqsYf7gXFNZsNc/iLayL3YIPlbzst/P8KE=,tag:IzDBEnHoo+DO54Ovs2GbIQ==,type:str]
    secret: ENC[AES256_GCM,data:h37N2LDLhDjcuAUUjkF/oOzR/FruJny1KjDX/ic5RCX2ZAbF0A/KtxKqwauiuVxiXb6+lIAq6ChSWhAFX3GEiQ==,iv:5vtBwxpiT8/L+YHwicRXU5A1t90j0xJvkUnOCDb2NUI=,tag:0WhRF1/0pvUrw94SImd06Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadXRrUzRhanBzeUh3TXo4
            SlJTeExmam9VRHpVZEQ0bjQvUUUzYlhXTlZzCmdBd1lQcGRSeDU4aUN4M2FoMlZr
            L3dRcFZtT1hvVkNacnV6NjE2ZGcyMGsKLS0tIGxJL0dVb1A3Rm80ZGh1bXpZZlRY
            K053c3VURmpSem1IM1l0ZmJEcTlmR1UK7StqCbqYiyTTYeL7HN5m0rS/xiHHWSF5
            jWE3Rg86IdYHKY1dY46GNdZ9E8yeth3ovqAkLPp+b/gaZev8oCupjg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g3x9w6x6wvskhtgn33wufdp2yn7vy8u3lf0f29r8nnkxuwrca4pscvydqy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDhENXluZyBBekFjZEZF
            MnhCQUVVZWJ1RTh5cWFvaGJkb0phbGE4N05LYWUwTWlxaEx4OQpaQ2J1R2FUNGF2
            WDZoM0pTV1NjMzczUlZjcDlRY20yakJCZDVSdk9PUVU0Ci0tLSBOWmxwZWM0bm84
            K0MrL2JsY3NraEg0MDZxU2ZjcndrRHRndllEdnc1VWFzCgOCWaVT8p+Zr9rpWper
            pjL9idQD5eA0MuVoCIIqdymeNLC3A7Tb0lY6g8U8w4E2J4wjNyd74ktyW0oxF3iv
            RFQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q0d8krn6cy32uun9ygwvrd373sp04hnjfpdfazy9lhpz70h3hauf2kgjzmx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDNweXF3ZyBBaEZaSnVZ
            aEtRbWVqQUdGcjJHWldjVUtNWStYMWJXRWppNDdqVmRwNms1SAorVWJaRC96bDdh
            NU9oWUx2RzBEN2JtcC8yYVZMVjBGdDEwdU4zaDJYSldrCi0tLSBBSTlrVlVaRVc4
            TEg1ZlU1b1JYRnFwZGhLKzhQV3N6dDlmaDdDc3FwYUN3CmvOu+dn6Jvfl1Ye7+E4
            yN5kEkL68SG83NB7cJPxml4QttVlt9xk81lKLXAH9+jgxBDG1/y6CvnnvNutL3VY
            V98=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwtampyck0fvqdlcfwjk3yhcu2s3gvrn67wdvxyv8uty6v5zpkxq76kzrpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T11:58:48Z"
    mac: ENC[AES256_GCM,data:y++Qy1azkRS5AIdBVdOJ+JhFolb2m2cN3GHr3F70tnIyE5yCfy0/pmr790YEvgxRdz9euXaLjEtFV7sUMwvj+esQRp1HvIsxwCwAxmHgdnlMIpCry0TdoN1MqZQohppH/Oh0FbdKLRTTdDvSVyD2sZFwiIN2IPGm/2DTOMnQn+I=,iv:M6M9i7q+eJkbLff0jFnRH4YpauPsxIQA/eJzdXQ0eKM=,tag:oYCB9Mw5XTzP4eKom0SmuQ==,type:str]
    version: 3.13.3
