apiVersion: v1
kind: Secret
metadata:
  name: hov1-s3
  namespace: forgejo
type: Opaque
stringData:
  ENDPOINT: https://213.128.185.82:443
  REGION: us-east-1
data:
  ca.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJiakNDQVJTZ0F3SUJBZ0lSQU9reVB2eDlUSWQvV1crS2R0bE1sM1F3Q2dZSUtvWkl6ajBFQXdJd0ZURVQKTUJFR0ExVUVBeE1LYUc5Mk1TQlRNeUJEUVRBZUZ3MHlOakE1TWpBeU1EVXlORGRhRncweU9UQTVNakF4TkRVeQpORGRhTUJVeEV6QVJCZ05WQkFNVENtaHZkakVnVXpNZ1EwRXdXVEFUQmdjcWhrak9QUUlCQmdncWhrak9QUU1CCkJ3TkNBQVF5ZWhPcjdrYTAvUU11UG9PbmNFVnpqU2NSUFJPUnJObWprSncxd05OMVVBZ2JveUtCS0xPdDF0bmUKMVZMN3VsUGxnY3pwZG5WUlYwNHpWZ2c5bkV5N28wVXdRekFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVApBUUgvQkFnd0JnRUIvd0lCQVRBZEJnTlZIUTRFRmdRVXJEVjlvMzhieFN1Q2RQNzJ2QTF6OHNVTkhYVXdDZ1lJCktvWkl6ajBFQXdJRFNBQXdSUUlnVk0zM3E1RVdVR1VaSVR0Zlg0SjFMUzBnWlhPaERZbU5vSFhScDFlaVJxWUMKSVFEYlpaTFdqN0xqOVBGMGU5OGozY3lQT2NpbnozZzkvZDRFR1h1RWhaaTVuQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
