apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: forgejo-postgres
  namespace: forgejo
spec:
  instances: 3
  storage:
    size: 64Gi
  bootstrap:
    initdb:
      database: forgejo
      owner: forgejo
