apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 1h
  releaseName: forgejo
  targetNamespace: forgejo
  chartRef:
    kind: OCIRepository
    name: forgejo-helm
    namespace: flux-system
  values:
    gitea:
      persistence:
        enabled: true
      admin:
        existingSecret: forgejo-admin
      oauth:
        - name: Zitadel
          provider: "openidConnect"
          autoDiscoverUrl: "https://zitadel.dataverket.org/.well-known/openid-configuration"
          existingSecret: forgejo-zitadel-oauth-secret
      config:
        database:
          DB_TYPE: postgres
          HOST: forgejo-postgres-rw:5432
          NAME: forgejo
          USER: forgejo
        mailer:
          enabled: true
          from: noreply@dataverket.org
          protocol: smtps
          smtp_addr: mail.nordhost.no
          smtp_port: 465
        service:
          ENABLE_INTERNAL_SIGNIN: false
          ENABLE_BASIC_AUTHENTICATION: false
          DISABLE_REGISTRATION: false
          SHOW_REGISTRATION_BUTTON: false
          ENABLE_NOTIFY_MAIL: true 
      additionalConfigFromEnvs:
        - name: FORGEJO__DATABASE__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-postgres-app
              key: password
        - name: FORGEJO__MAILER__USER
          valueFrom:
            secretKeyRef:
              name: forgejo-mailer
              key: username
        - name: FORGEJO__MAILER__PASSWD
          valueFrom:
            secretKeyRef:
              name: forgejo-mailer
              key: password
    tcpRoute:
      enabled: true
      parentRefs:
        - name: envoy-gateway
          namespace: envoy-system
          sectionName: ssh
      hostnames:
        - git.dataverket.org
      port: 22
    httpRoute:
      enabled: true
      parentRefs:
        - name: envoy-gateway
          namespace: envoy-system
          sectionName: https
      hostnames:
        - git.dataverket.org
      port: 3000
