apiVersion: v1
kind: Secret
metadata:
    name: nordhost-config
    namespace: cert-manager
type: Opaque
stringData:
    config.json: ENC[AES256_GCM,data:7y7yepvDIPcsxY1RawMrKm6aQWt6Iidg491jJe0BIsluppldLHqgYGD7p46+D3nkARz6fm0VL5sB5AvfYqdhrLW82yfu+owxB95179BJImWEH1VJkIAAIMpfafgEtBW/+PF5ZaC56a8nT0C9OwzZ7GhaYPWQ3O1wm5y3KokTOypGdSr+EzCfqP+kdBubZcygiEHgR8jrMrwMg69VsIrLC2yty+4+lna6Q/WPGpqVD01Okz4uXPqMTuUpdTuFWAZbZ/Hd5iRp2R5EQz0t4GdZeKybps80FcBwkv7r2ZlecDkiOTD1X5XAUMfrsjSJbW8VAgXMeOd50gIa51iI9eIE34w9gCJOXlzR5qoO2FopC6zE0CujGpYTPTixg092LAdiTd7wyTffKTaFYyijJEFYGKTXVPQJutrQ+Bu0os/26ePBdzxsWfOPhddzFjiCTRIz6SclFpFNZ1rMrXNXtnY=,iv:f/+o3Jn+jvpUEjqVen1ntd5af4cVNA0SDiucYaMtcwA=,tag:c/Qzst3DFR6nR7WvGi0s0g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcGZDRXBLS2JZQUJ1NS9N
            UG5KUmk1QVA0UkM0aWJuemVmdEhvb2JxYUVVCjlHVlVkWWozam9zM3ZmNzFmaDJX
            ci9tVmpFTjVKdXlPV0M4SmdnaGpubkkKLS0tIEpETzlwTFBwQUpGeDRJL01OSHVO
            anN3dDdpZFFINjI5clVKcEFOY2VVb2MKy0Kza1M+aP87JbDzNwCocQ589JsgwYdX
            758Y9ha2mMDDRALieyuzD6x59XtsbL1WiJz7JaeaR/g34/ATgdM29A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g3x9w6x6wvskhtgn33wufdp2yn7vy8u3lf0f29r8nnkxuwrca4pscvydqy
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDhENXluZyBBK3BPTmZC
            RXorVzVRa0pBL2hrMmNPd1BYdGNzSVF4QlRjbEVoWTcwYWhxNApOcmRhaXp0dHF4
            SklHZVIyQkhKS1VDTXNYQzY1VkpUL3dnUjd5TVA0TDdZCi0tLSA5ZzRXWG9waE5n
            Z3ZKRnVHd2RYdU1qaTU2ek1XWGRZYloyQUErbEFrVFlRCkstKS4rg8MSZbjDfS/j
            P7J6yxJwtpxmHhqnPDrnDG2jwRbfmH/kreqrwOX0walBiCYEIax6Ky/smT9NXMVV
            +zk=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1q0d8krn6cy32uun9ygwvrd373sp04hnjfpdfazy9lhpz70h3hauf2kgjzmx
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IDNweXF3ZyBBMXRTRk1z
            TkNLRXBRM0VWYkJid1ptdkUrUmhzYkh5cExqYUxVSFVMQWplSQpIalh5aUJabGkw
            bEVqaEhZMmdXSkJqa0pHaGxtNDJHcFZFS1RsVGZLL2RNCi0tLSBpaFA1UnJXaGVI
            MTFmdnpGUFpYZnNiRXQ4YmsvdlEwMUM5Ly84d01LdmZ3CngQWc8AHTJLLxtgNm1y
            Erhntt+YNT+Sa2MLXV0WCLcGTZa3togqkG5ahNQCF6W+6mv1uh6GB38ct3+AOpmS
            zWQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yubikey1qwtampyck0fvqdlcfwjk3yhcu2s3gvrn67wdvxyv8uty6v5zpkxq76kzrpw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-05T11:54:25Z"
    mac: ENC[AES256_GCM,data:xMbehhGGlWaPcxW8Zu021nKSR8DrGSjP17ODyPE0CzpGNkmaGJ34A6ESTssHRrWu5mS6K9kFcAgldf8S7drKnSj1dcPXebFcPgYcFBCbj73QxKp9Vgd3t3+z0qvEdSbJ/SorpUXFq7Y1/0Ec/IIoLLA0hwTLogUw5mzfPD/JJqw=,iv:9R1sV2v2TEBYgbXWYZEcoy+r+7RSztxSdlKIgxKIHEk=,tag:bjzwViPAC7lD6TcZbBDX2g==,type:str]
    version: 3.13.3
